spring.application.name=API-GATEWAY

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ==============================
# JWT
# ==============================
jwt.secret=MySuperSecretKeyForMicroservicesJwtAuthentication2026

# ==============================
# User Service
# ==============================
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

# ==============================
# Order Service
# ==============================
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/orders/**

# ==============================
# Payment Service
# ==============================
spring.cloud.gateway.server.webmvc.routes[2].id=payment-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/payments/**